CVE-2014-3730 and CVE-2018-7536 completed
VulnerabilityHistoryProject/django-vulnerabilities pull request #13
Opened 2020-04-01 04:00 UTC by jtd8414

Completed CVE-2014-3730 and CVE-2018-7536

2020-04-02 00:07 UTC, saf6260 reviewed
Overall really great job explaining the issues and I thought you had a lot of really good details and information about the Vulnerabilities! Great job. Since I'm limited to 10 upvotes, I'll give you some after looking at my other one :)

2020-04-02 00:07 UTC, saf6260 commented on cves/CVE-2014-3730.yml
> +reported_date: 2014-05-14
Looking at your fixing commits below, could you see if maybe those commits were from a different report date? It seems like since the commits occurred on 2014-05-12 that they were aware of the issue before the 14th

2020-04-02 00:07 UTC, saf6260 commented on cves/CVE-2014-3730.yml
> +  A vulnerability classified as critical was found in Django, it can be initiated remotely and with no
I think this description could flow a little easier to the reader. For example, saying "a critical vulnerability that allowed ____ was found in Django". It may help catch the reader's attention a little more, as mentioning its critical may be better associated if its mentioned closer to the description

2020-04-02 00:07 UTC, saf6260 commented on cves/CVE-2014-3730.yml
> +    vulnerability was found in this function as well, and that fix still did not result in unit tests, which was a mistep to be sure. If there had been a
It may be helpful here to mention the commit hash of the other vulnerability that you mentioned here, in case the reader wants to check it out or see the progression you saw

2020-04-02 00:07 UTC, saf6260 commented on cves/CVE-2014-3730.yml
> +CWE: 20
Could you add some reasoning to why this meets CWE 20 under the CWE note?

2020-04-02 00:07 UTC, saf6260 commented on cves/CVE-2018-7536.yml
> +reported_date: 2018-03-06
Could you also investigate a little further here? Similar to my other comment, it seems like the vulnerability also was reported a little earlier if commits happened to fix this 2-24-2018

2020-04-02 00:07 UTC, saf6260 commented on cves/CVE-2018-7536.yml
> +    applies: False
Since this lasted for 13 years, I feel like this problem may also apply to secure by default, as the developer didnt think this was an issue. If you agree, could you discuss this a litte?

2020-04-03 03:17 UTC, saf6260 reviewed
Now that I've reviewed the other CVE's, I wanted to give upvotes, so those are as follows:
CVE-2014-3730: 4
CVE-2018-7536: 2
Always interesting to see vulnerabilities that are web-accessible, especially when its in a method thats supposed to protect against those types of attacks.
Good job again with this!

2020-04-03 18:47 UTC, srf6413 requested changes
Great job here! Pretty much everything was enumerated in a clear, concise, and detailed way. There were definitely minimal suggestions for changes, just a few spots that I mentioned where it could be improved slightly. I enjoyed reading both of them nice work!

**Upvotes:**
CVE-2014-3730 - 3
CVE-2018-7536 - 2

2020-04-03 18:47 UTC, srf6413 commented on cves/CVE-2014-3730.yml
> +  answer: Peter Kuma and Gavin Wahl reported the issue to Django.
You could expand a little more here on how they found the issue, if you can find information on it that is

2020-04-03 18:47 UTC, srf6413 commented on cves/CVE-2014-3730.yml
> +  answer_note: One way of finding the vulnerability was to pass in a url like http:\\\djangoproject.com, passing in malformed URLs would be easily done by an automated tool.
Consider replacing "would" with "could"

2020-04-03 18:47 UTC, srf6413 commented on cves/CVE-2014-3730.yml
> +  answer_note: One way of finding the vulnerability was to pass in a url like http:\\\djangoproject.com, passing in malformed URLs would be easily done by an automated tool.
Consider replacing "like" with "such as".

2020-04-03 18:47 UTC, srf6413 commented on cves/CVE-2014-3730.yml
> +        in doing so introduced a vulnerability. Additionally it can be seen that no unit tests are implemented with this initial commit. If the author
Consider changing"are" to "were. Great point here! I bet theres a good chance they could've spotted the vulnerability if they would have tested.

2020-04-03 18:47 UTC, srf6413 commented on cves/CVE-2014-3730.yml
> +        This commit is interesting because this commit was about fixing a different vulnerability having to do with rejecting incorrect schemes,
Seems like you can replace the second occurrence of "this commit" with "it" or something.

2020-04-03 18:47 UTC, srf6413 commented on cves/CVE-2014-3730.yml
> +      The vulnerability can be exploited by sending in input that wasn't validated.
Consider adding "an" so it reads "sending in an input"

2020-04-03 18:47 UTC, srf6413 commented on cves/CVE-2014-3730.yml
> +    considered when you are designing any piece of software large or small.
Response here was great!

2020-04-03 18:47 UTC, srf6413 commented on cves/CVE-2018-7536.yml
> +  answer: James Davis reported the vulnerability to Django.
Same comment here as the other one. No worries if you cannot find any more information than this.

2020-04-03 18:47 UTC, srf6413 commented on cves/CVE-2018-7536.yml
> +    applies: False
I also agree that this problem would be a great example of this.

2020-04-05 23:15 UTC, jtd8414 commented on cves/CVE-2014-3730.yml
> +  answer: Peter Kuma and Gavin Wahl reported the issue to Django.
This is all I could find, I believe they reported the vulnerability internally, I found no mention online as to how they made this discovery, only that they are credited.

2022-10-15 22:47 UTC, merged