CVE-2014-0482
VulnerabilityHistoryProject/django-vulnerabilities pull request #20
Opened 2020-04-01 18:56 UTC by sjc5897

Small Django vulnerability in their middleware that allowed remote users to receive other user's session.

2020-04-01 19:00 UTC, sjc5897 commented
I have 2 django vulnerabilities, I thought it was one django one tomcat

2020-04-03 19:20 UTC, jmc9961 reviewed
I'm not sure exactly how the upvotes are supposed to work, so I guess I will give one to each?

2020-04-03 19:20 UTC, jmc9961 commented on cves/CVE-2014-0482.yml
> +reported_date: 2014-07-21
Would you mind clarifying where you found this date?

2020-04-03 19:20 UTC, jmc9961 commented on cves/CVE-2014-0482.yml
> +    vulnerability was created as misunderstanding of the interaction between the
There should be an 'a' between 'as' and 'misunderstanding'

2020-04-03 19:20 UTC, jmc9961 commented on cves/CVE-2014-0482.yml
> +    design mistake; however, I have been unable to find designs to show this.
Could you clarify on how you would argue that it is also a design mistake here?

2020-04-03 19:20 UTC, jmc9961 commented on cves/CVE-2018-14574.yml
> +    sending internationally malformed urls; however, you may need a very specific
Did you mean to say 'intentionally' instead of 'internationally'?

2020-04-03 19:20 UTC, jmc9961 commented on cves/CVE-2018-14574.yml
> +      Part of the issue that caused this security vulnrability elimnated some input validation.
'vulnerability' and 'eliminated' are misspelled.

2020-04-03 19:20 UTC, jmc9961 commented on cves/CVE-2018-14574.yml
> +    optimization opportunity was also the person who commit the optimization and thus
'commit' should be 'committed'

2020-04-03 23:51 UTC, dad9489 requested changes

2020-04-03 23:51 UTC, dad9489 commented on cves/CVE-2014-0482.yml
> +    This vulnerability requires understanding of authentication requirements for RemoteUserMiddleware
It is not clear why this understanding would prevent an automatic tool from detecting this as long as it was designed by someone with this understanding. Maybe elaborate?

2020-04-03 23:51 UTC, dad9489 commented on cves/CVE-2018-14574.yml
> +  URL that can lead to redirects to other sites.
This should either say " a maliciously crafted URL" or "maliciously crafted URLs"

2020-04-03 23:51 UTC, dad9489 commented on cves/CVE-2018-14574.yml
> +  code_answer: This file had unit tests; however, no unit test were created to catch this edgecase
should be " no unit tests" and "edge case"

2020-04-03 23:51 UTC, dad9489 commented on cves/CVE-2018-14574.yml
> +    I would say that this is a mistake in the Requirements of the project. This
I don't understand what you mean by this being a mistake in the requirements. I get that this was introduced by an optimization that was not properly reviewed, but I don't see how that is caused by the requirements. Maybe explain a bit more what you mean by this?

2020-04-04 00:27 UTC, dad9489 commented on cves/CVE-2014-0482.yml
> +CWE: 1211
Upvotes: 2

2020-04-04 00:27 UTC, dad9489 commented on cves/CVE-2018-14574.yml
> +CWE: 601
Upvotes: 3

2020-04-07 17:57 UTC, sjc5897 commented on cves/CVE-2014-0482.yml
> +reported_date: 2014-07-21
https://code.djangoproject.com/ticket/23066 I was able to find a django ticket. The ticket number was found in a commit message.

2022-10-15 22:46 UTC, merged