CVE-2014-0483 and CVE-2018-16984
VulnerabilityHistoryProject/django-vulnerabilities pull request #43
Opened 2020-04-02 03:26 UTC by jmc9961

Pull request for CVE-2014-0483 and CVE-2018-16984

2020-04-03 15:11 UTC, sjc5897 commented on cves/CVE-2014-0483.yml
> +published_date: 2014-08-20
When Researching my Django vulnerabilities, I noticed that they tend to publish the release before the disclosure. I'd double check the date.

2020-04-03 15:23 UTC, sjc5897 commented on cves/CVE-2018-16984.yml
> +    a reason to need the password, then it might be better to not send the
This sentence is a bit confusing.

2020-04-03 15:27 UTC, sjc5897 commented on cves/CVE-2014-0483.yml
> +  to_field parameter. There was no check in place to verify that field being
What is the to_field parameter?

2020-04-03 15:27 UTC, sjc5897 commented on cves/CVE-2014-0483.yml
> +CWE: CWE-264
Upvote:2

2020-04-03 15:29 UTC, sjc5897 commented on cves/CVE-2018-16984.yml
> +CWE: CWE-522
Upvote: 3

2020-04-03 21:00 UTC, dajanio commented on cves/CVE-2014-0483.yml
> +  to_field parameter. There was no check in place to verify that field being
Maybe the description should not contain project specific terms... though I am not sure if this is one.

2020-04-03 21:00 UTC, dajanio commented on cves/CVE-2014-0483.yml
> +  developer: true
I'm not sure... is this supposed be true if the person that found the vulnerability was a google employee? If so, how do you know that he is one?

2020-04-03 21:00 UTC, dajanio commented on cves/CVE-2014-0483.yml
> +    This vulnerability was not related to translation, typography, text, etc.
How did you come to this conclusion?

2020-04-03 21:00 UTC, dajanio commented on cves/CVE-2018-16984.yml
> +    I chose admin because according to the write up in the vulnerability
Was there something like a path that could help you determine what the name of the actual component was? It very well have been named admin however.

2020-04-03 21:00 UTC, dajanio commented on cves/CVE-2018-16984.yml
>      they have written there. Are they doing those? Does the fix look proper?
Could this also be security by obscurity due to the existence of the hashed passwords?

2020-04-03 21:00 UTC, dajanio commented on cves/CVE-2018-16984.yml
> +CWE_note: |
Upvote: 5

2020-04-03 21:00 UTC, dajanio commented on cves/CVE-2014-0483.yml
> +CWE_note: |
Upvote: 2

2020-04-04 00:02 UTC, dad9489 commented
Github won't let me comment on unchanged lines, but I think it is pretty likely that not all of the VCCs that were automatically found are relevant. I would recommend going through each and checking to make sure they are actually relevant to this CVE

2020-04-04 00:28 UTC, dad9489 requested changes

2020-04-04 00:28 UTC, dad9489 commented on cves/CVE-2014-0483.yml
> +  was not intended to be seen using this method could be accessed in this way.
The phrase "that was not intended to be seen using this method could be accessed in this way" sounds a little awkward to me. Maybe reword this?

2020-04-04 00:28 UTC, dad9489 commented on cves/CVE-2014-0483.yml
>  interesting_commits:
Is there a reason you were not able to find interesting commits?

2020-04-04 00:28 UTC, dad9489 commented on cves/CVE-2014-0483.yml
> +      Users needed to have permission to view a information about a particular
That "a" is unnecessary

2020-04-04 00:28 UTC, dad9489 commented on cves/CVE-2014-0483.yml
> +    oversite. The developers did have security in mind when they designed the
oversight not oversite

2020-04-04 00:28 UTC, dad9489 commented on cves/CVE-2018-16984.yml
> +    password to hte view at all, whether it is hashed, hidden, or otherwise. I
Typo - should be "the" not "hte"

2020-04-04 00:29 UTC, dad9489 commented on cves/CVE-2018-16984.yml
> +CWE: CWE-522
Upvotes: 4

2020-04-04 00:29 UTC, dad9489 commented on cves/CVE-2014-0483.yml
> +CWE: CWE-264
Upvotes: 1

2020-04-09 02:18 UTC, jmc9961 commented on cves/CVE-2014-0483.yml
> +published_date: 2014-08-20
The four releases related to this vulnerability, Django 1.4.14, Django 1.5.9, Django 1.6.6, and Django 1.7 release candidate 3, are tagged August 20th, 2014, as can be seen here: https://github.com/django/django/releases?after=1.6.8

2020-04-09 02:45 UTC, jmc9961 commented on cves/CVE-2018-16984.yml
> +    I chose admin because according to the write up in the vulnerability
There's not any particular subsystem or path called out in the disclosure https://www.djangoproject.com/weblog/2018/oct/01/security-release/
The files touched by the commit that fixed the vulnerability were:
django/contrib/admin/helpers.py
django/contrib/auth/forms.py
docs/releases/2.1.2.txt
tests/auth_tests/test_views.py

So I felt that admin was a close enough fit considering what the vulnerability was.

2020-04-09 03:08 UTC, jmc9961 commented on cves/CVE-2014-0483.yml
> +  to_field parameter. There was no check in place to verify that field being
I am not entirely clear on what the to_field parameter is myself, I included it because it was in the original description of the CVE. The CVE https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0483 didn't describe what it was, and only said that it was the means through which sensitive data could be exposed, so I felt it was relevant enough to keep in.

2020-04-09 03:12 UTC, jmc9961 commented on cves/CVE-2014-0483.yml
> +  to_field parameter. There was no check in place to verify that field being
If you're referring to the to_field parameter, here is what I mentioned to another person who asked about it above:

I included it because it was in the original description of the CVE. The CVE https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0483 didn't describe what it was, and only said that it was the means through which sensitive data was being exposed, so I felt it was relevant enough to keep in.

2020-04-09 03:15 UTC, jmc9961 commented on cves/CVE-2014-0483.yml
> +  developer: true
I thought that the flag was supposed to be true if the person who found the bug was a developer on the project. The person credited with discovering the bug, Collin Anderson, is a contributor to the Django project, though I could not find any sort of bug report or commits linking him to this specific vulnerability.

2020-04-09 03:17 UTC, jmc9961 commented on cves/CVE-2014-0483.yml
> +    This vulnerability was not related to translation, typography, text, etc.
Because there is nothing to do with internationalization in this vulnerability. 
The vulnerability had to do with a flaw in the way that one of the admin features was implemented that potentially allowed for sensitive data to be compromised if it was exploited.

2022-10-15 21:21 UTC, merged